#!/usr/bin/env node
// Writes .env for local development if it does not exist: fresh random secrets and a localhost
// base URL. Never overwrites an existing .env.

import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';

const path = new URL('../.env', import.meta.url);
if (existsSync(path)) {
  console.log('.env exists; leaving it alone');
  process.exit(0);
}

const secret = () => randomBytes(32).toString('base64');
writeFileSync(
  path,
  `# Local development only — generated by scripts/dev-env.mjs
NODE_ENV=development
PORT=3200
BASE_URL=http://localhost:3200
POSTGRES_PASSWORD=foreman
DATABASE_URL=postgresql://foreman:foreman@127.0.0.1:5532/foreman
KEK=${secret()}
PEPPER=${secret()}
COOKIE_KEYS=${secret()}
OPERATOR_EMAIL=dev@localhost
OPERATOR_DISPLAY_NAME=Developer
# Local only, and fixed on purpose: the seed otherwise generates a random password and prints it
# once, which the e2e suite cannot know — so \`pnpm e2e\` could not sign in on a fresh stack. CI
# sets its own.
OPERATOR_PASSWORD=foreman-dev-password-9174
BACKUP_DIR=./backups
# Local only. The e2e suite signs its own deliveries with this to exercise the ingest path.
GITHUB_WEBHOOK_SECRET=dev-webhook-secret
`,
  { mode: 0o600 },
);
console.log('wrote .env with fresh local secrets');
